### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by brckd** [Epikest/penis#2]
me and my frends want to play penis but [penis.epik.ml](https://penis.epik.ml) is down :<
[github pages](https://epikest.github.io/penis) also redirects me to the same website >_<

can u pls either
- restart [penis.epik.ml](https://penis.epik.ml)
- use [github pages](https://epikest.github.io/penis) as backup
- or else im gonna fork the repo and host penis myself >:D

**Comment by Epikest** [comment]
the domain expired and i am unable to renew it, i'll deploy it on Cloudflare pages and update any URLs
